// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC8sjhPDCR3oPuahSVRtR7sv06NsLYYGk',
    appId: '1:1073922732520:android:38eab76c219401b6f5b45d',
    messagingSenderId: '1073922732520',
    projectId: 'wowo-f635b',
    databaseURL: 'https://wowo-f635b-default-rtdb.firebaseio.com',
    storageBucket: 'wowo-f635b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiKDN2kdPKWHHBbB7XC7onFkpEPwJCQDM',
    appId: '1:1073922732520:ios:64906cb7ca44a8fef5b45d',
    messagingSenderId: '1073922732520',
    projectId: 'wowo-f635b',
    databaseURL: 'https://wowo-f635b-default-rtdb.firebaseio.com',
    storageBucket: 'wowo-f635b.firebasestorage.app',
    androidClientId: '1073922732520-8cs37b8g5a4pfbjdiletlnsnk7rgbi3d.apps.googleusercontent.com',
    iosClientId: '1073922732520-2jd0aqlunvd0drqnrltre757741hb4de.apps.googleusercontent.com',
    iosBundleId: 'com.wowww.app',
  );

}